# Every static lesson plot is generated from the executable lab objects.
suppressPackageStartupMessages({library(ggplot2); library(patchwork)})
save_plot <- function(p, path, w = 10, h = 5) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  ggsave(path, p, width = w, height = h, dpi = 140)
}
pdf(tempfile(fileext = ".pdf"))
e <- new.env(parent = globalenv())
sys.source("labs/04-variable-features-lab.R", e)
save_plot(e$toy_plot, "figures/module-04/toy-mean-variance.png")
save_plot(e$mean_variance_plot + e$top_hvg_plot, "figures/module-04/mean-variance-and-hvgs.png", 12)
save_plot(e$pca_plot, "figures/module-04/hvg-count-pca-comparison.png", 11)
save_plot(e$schematic_plot, "figures/module-04/schematic.png", 8)
e <- new.env(parent = globalenv())
sys.source("labs/05-scaling-regression-lab.R", e)
save_plot(e$scale_plot, "figures/module-05/normalized-versus-scaled.png")
save_plot(e$pca_scale_plot, "figures/module-05/unscaled-versus-scaled-pca.png")
save_plot(e$reference_plot, "figures/module-05/reference-population-scaling.png")
save_plot(e$regression_plot, "figures/module-05/regression-pca-comparison.png", 13)
save_plot(e$mapping_plot, "figures/module-05/mapping.png")
save_plot(e$distribution_plot, "figures/module-05/distributions.png")
save_plot(e$regression_distribution_plot, "figures/module-05/regression-distributions.png")
e <- new.env(parent = globalenv())
sys.source("labs/06-pca-lab.R", e)
save_plot(e$geometry_plot, "figures/module-06/geometry.png", 7)
save_plot(e$loading_plot, "figures/module-06/loadings.png", 10, 11)
save_plot(e$variance_plot, "figures/module-06/variance.png", 7)
save_plot(e$subset_plot, "figures/module-06/subset.png", 11)
e <- new.env(parent = globalenv())
sys.source("labs/07-choosing-dimensions-lab.R", e)
save_plot(e$dims_plot, "figures/module-07/dims.png", 11, 12)
save_plot(e$marker_plot, "figures/module-07/markers.png", 9)
dev.off()
message("Representation figures generated successfully.")
